# This file is autogenerated from update.sh in the same directory.
{
  gwenhywfar.version = "4.99.20rc4";
  gwenhywfar.sha256 = "0dcsqz013fgqiwg4dl51jw25fjvwn9fs7b56kfn90h47b9gfakng";
  gwenhywfar.releaseId = "168";
  libchipcard.version = "5.1.3beta";
  libchipcard.sha256 = "0fj2h39ll5kiv28ch8qgzdbdbnzs8gl812qnm660bw89rynpjnnj";
  libchipcard.releaseId = "138";
  aqbanking.version = "5.99.39beta";
  aqbanking.sha256 = "03i5axbv23m4smnlp9124jgmzazjxqfg2d5wgnsvg4kd5z0h15rz";
  aqbanking.releaseId = "193";
}
